
url : https://justine-and-fred.github.io
baseurl: /justine-and-fred/

# Site settings
title: Mariage de Justine et Fred
email: justine.and.fred@gmail.com
description: "Nous nous marions !"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ec382f
  secondary: ec382f  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Administration communale de Hamoir
  pic: 1
  position: rue de Tohogne 14 4180 Hamoir
  social:
    - title: #
      url: #
    - title: #
      url: #
    - title: #
      url: #

- name: Hostellerie du Saint Roch
  pic: 2
  position: Rue du Parc - Vallee De L'Ourthe, 4180 Comblain-au-Pont
  social:
    - title: #
      url: #
    - title: #
      url: #
    - title: #
      url: #



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 1 rue du Ruisseau
  - line: 4180 Hamoir 

# Build settings
markdown: kramdown
permalink: pretty